/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vivispizza;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import metodos_sql.Encriptar;
import metodos_sql.conexiondb;
import metodos_sql.metodos_sql;
import static vivispizza.login.texto;

/**
 *
 * @author chris
 */
public class Add_Supr_usuario extends javax.swing.JFrame {
        Encriptar enc = new Encriptar();
    /**
     * Creates new form Add_Supr_usuario
     */
    public Add_Supr_usuario() {
        initComponents();
        setLocationRelativeTo(null);
        actualizartabla();
      
    }
      metodos_sql metodos = new metodos_sql();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnagregar = new javax.swing.JButton();
        btnregresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        txtnombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtusuarios = new javax.swing.JTable();
        btnbuscar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnagregar.setText("Agregar");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        btnregresar.setText("Regresar");
        btnregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre:");

        jLabel2.setText("Contraseña:");

        jtusuarios = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jtusuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Usuario", "Password"
            }
        ));
        jtusuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtusuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtusuarios);

        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtpassword))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnagregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(37, 37, 37)
                        .addComponent(btnbuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(39, 39, 39)
                        .addComponent(btneliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(31, 31, 31)
                        .addComponent(btnregresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(130, 130, 130))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnbuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnregresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btneliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnagregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        String cadenaEncriptada = enc.encriptar("SomosProgramadores", txtpassword.getText());
        if ("".equals(txtnombre.getText())){
            JOptionPane.showMessageDialog(this, "Completar los campos por favor");
        }else{if ("".equals(txtpassword.getText())){
            JOptionPane.showMessageDialog(this, "Completar los campos por favor");
        } else{
          int i = metodos.guardar(txtnombre.getText(), cadenaEncriptada);
            if (i > 0) {
              JOptionPane.showMessageDialog(this, "Datos guardados correctamente");
           } else {
                JOptionPane.showMessageDialog(this, "No se pudo guardar los datos");
            }
        }
        }
        txtnombre.setText("");
        txtpassword.setText("");
        actualizartabla();
         
    }//GEN-LAST:event_btnagregarActionPerformed

    private void btnregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresarActionPerformed
           Menu_principal ventana = new Menu_principal();
           if(texto!=null){
               ventana.labelusuario.setText(texto.toUpperCase());
               System.out.print("bobo");
           }
                ventana.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_btnregresarActionPerformed

    private void jtusuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtusuariosMouseClicked
        // TODO add your handling code here:
        Connection conexion = null; 
        PreparedStatement ps = null;
            ResultSet rs = null;
             try{
           conexion = conexiondb.getConexion();          
            int Fila = jtusuarios.getSelectedRow();
            String nombre = jtusuarios.getValueAt(Fila,0).toString();
            
            ps = conexion.prepareStatement("SELECT nombre,password FROM Usuarios WHERE nombre=?");
            ps.setString(1, nombre);
            rs = ps.executeQuery();
            while (rs.next()){
                txtnombre.setText(rs.getString("Nombre"));
                txtpassword.setText(rs.getString("Password"));
            }
              conexion.close();
             } catch (SQLException ex) {
                 System.out.println(ex.toString());
        }
        
        
        
        
        
    }//GEN-LAST:event_jtusuariosMouseClicked

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
          Connection conexion = null;
          String campo = txtnombre.getText();
                String where = "";
                if (!"".equals(campo)){
                    where = "WHERE nombre like '"+"%"+campo+"%"+"'";
                    
                }
        
        try{
            conexion = conexiondb.getConexion();
            DefaultTableModel modelo = new DefaultTableModel();
            jtusuarios.setModel(modelo);
            PreparedStatement ps = null;
            ResultSet rs = null;
            
            
            String sql = "SELECT nombre, password FROM Usuarios "+where;
            System.out.println(sql);
            ps = conexion.prepareStatement(sql);
            rs = ps.executeQuery();
            
            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();
            modelo.addColumn("Nombre");
            modelo.addColumn("Password");
            int [] anchos = {50,200,50,50};
            for (int x = 0; x<cantidadColumnas; x++)
            {
                jtusuarios.getColumnModel().getColumn(x).setPreferredWidth(anchos[x]);
            }
            
            while (rs.next()){
                
                Object[] filas = new Object[cantidadColumnas];
                for(int i = 0;i<cantidadColumnas;i++){
                    filas[i]= rs.getObject(i+1);
               }
                modelo.addRow(filas);               
            }   
           rs.close();
           ps.close();
            conexion.close();
        } catch(SQLException ex) {
            System.err.println(ex.toString());
            
        }
          txtnombre.setText("");
          txtpassword.setText("");
             
        
    }//GEN-LAST:event_btnbuscarActionPerformed

          //Mostrar Jtable
       public  DefaultTableModel actualizartabla(){
           Connection conexion = null;     
                    try{
           conexion = conexiondb.getConexion(); 
           DefaultTableModel modelo = new DefaultTableModel();
           
           jtusuarios.setModel(modelo);
            PreparedStatement ps = null;
            ResultSet rs = null;
       
            String sql = "SELECT nombre, password FROM Usuarios ";
            System.out.println(sql);
            ps = conexion.prepareStatement(sql);
            rs = ps.executeQuery();
            
            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();
            modelo.addColumn("Nombre");
            modelo.addColumn("Password");
            int [] anchos = {50,200,50,50};
            for (int x = 0; x<cantidadColumnas; x++)
            {
                jtusuarios.getColumnModel().getColumn(x).setPreferredWidth(anchos[x]);
            }
            
            while (rs.next()){
                
                Object[] filas = new Object[cantidadColumnas];
                for(int i = 0;i<cantidadColumnas;i++){
                    filas[i]= rs.getObject(i+1);
               }
                modelo.addRow(filas);               
            } 
            rs.close();
            ps.close();
            conexion.close();
        } catch(SQLException ex) {
            System.err.println(ex.toString());
        }         
        return null;
       }
    
    
    
    
    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
          Connection conexion = null;   
          PreparedStatement ps = null;
             
             try{
               conexion = conexiondb.getConexion();  
            int Fila = jtusuarios.getSelectedRow();
            String nombre = jtusuarios.getValueAt(Fila,0).toString();
            
            ps = conexion.prepareStatement("DELETE FROM Usuarios WHERE nombre=?");
            ps.setString(1, nombre);
            ps.execute();
            JOptionPane.showMessageDialog(this, "Datos eliminados");
               ps.close();
               conexion.close();
             } catch (SQLException ex) {
                 System.out.println(ex.toString());
                
            }
             txtnombre.setText("");
             txtpassword.setText("");
             actualizartabla(); 
    
    }//GEN-LAST:event_btneliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Supr_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Supr_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Supr_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Supr_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Supr_usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnregresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtusuarios;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JPasswordField txtpassword;
    // End of variables declaration//GEN-END:variables
}
