/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vivispizza;

import javax.swing.JOptionPane;
import metodos_sql.Encriptar;
import metodos_sql.metodos_sql;

/**
 *
 * @author chris
 */
public class login extends javax.swing.JFrame {
         Encriptar enc = new Encriptar();
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        setLocationRelativeTo(null);
       // rsscalelabel.RSScaleLabel.setScaleLabel(lbfondo,"src/imagenes/20200221_114111_0000.png");
        //rsscalelabel.RSScaleLabel.setScaleLabel(lblLOgin,"src/imagenes/login2.png");
        ///mnt/2BB12D737F92C9C5/software vivis pizza/vivispizza/build/classes/imagenes
        rsscalelabel.RSScaleLabel.setScaleLabel(lblLOgin,"build/classes/imagenes/login2.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(lbfondo,"build/classes/imagenes/20200221_114111_0000.png");
        txtnombre.setBackground(new java.awt.Color(0,0,0,1));
        txtpasswd.setBackground(new java.awt.Color(0,0,0,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public  static String texto;
     metodos_sql metodos = new metodos_sql();
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btningresar = new javax.swing.JButton();
        txtpasswd = new javax.swing.JPasswordField();
        txtnombre = new javax.swing.JTextField();
        lbfondo = new javax.swing.JLabel();
        lblLOgin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btningresar.setBorder(null);
        btningresar.setContentAreaFilled(false);
        btningresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningresarActionPerformed(evt);
            }
        });
        getContentPane().add(btningresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 460, 80, 40));

        txtpasswd.setForeground(new java.awt.Color(255, 255, 255));
        txtpasswd.setBorder(null);
        getContentPane().add(txtpasswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 480, -1));

        txtnombre.setForeground(new java.awt.Color(255, 255, 255));
        txtnombre.setBorder(null);
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 480, 20));

        lbfondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/20200221_114111_0000.png"))); // NOI18N
        getContentPane().add(lbfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 110, 110));

        lblLOgin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/login2.png"))); // NOI18N
        getContentPane().add(lblLOgin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
         
    }//GEN-LAST:event_txtnombreActionPerformed

    private void btningresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresarActionPerformed
        // TODO add your handling code here:
          String cadenaEncriptada = enc.encriptar("SomosProgramadores", txtpasswd.getText());
          String busqueda_usuario = metodos.buscarUsuarioRegistrado(txtnombre.getText(),cadenaEncriptada );
         
        if (txtnombre.getText().equals("root") && txtpasswd.getText().equals("12345")) {
           texto = "Administrador";
           
            JOptionPane.showMessageDialog(this, "Bienvenido iniciaste sesion como root (Administrador)");
             Menu_principal ventana = new Menu_principal();
            ventana.labelusuario.setText("Administrador".toUpperCase());
            ventana.setVisible(true);
            this.dispose();

        } else if (busqueda_usuario.equals("usuario encontrado")) {
            String busqueda_nombre = metodos.buscarnombre(txtnombre.getText());
            texto=txtnombre.getText();
            JOptionPane.showMessageDialog(this, "Bienvenido (a)\n" + busqueda_nombre.toUpperCase());
            Menu_principal ventana = new Menu_principal();
           ventana.labelusuario.setText(busqueda_nombre.toUpperCase());
            ventana.setVisible(true);
           this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Usuario no registrado");
        }
    }//GEN-LAST:event_btningresarActionPerformed
          //Como encriptar y desencriptar 
          /*String cadenaAEncriptar = JOptionPane.showInputDialog("Ingresar la cadena a encriptar");
          String cadenaEncriptada = enc.encriptar("SomosProgramadores", cadenaAEncriptar);
          JOptionPane.showMessageDialog(null, "Cadena Encriptada: "+ cadenaEncriptada);
          String cadenaDesencriptada = enc.desencriptar("SomosProgramadores", cadenaEncriptada);
          JOptionPane.showMessageDialog(null, "Cadena Desencriptada:"+cadenaDesencriptada);*/
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new login().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btningresar;
    private javax.swing.JLabel lbfondo;
    private javax.swing.JLabel lblLOgin;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JPasswordField txtpasswd;
    // End of variables declaration//GEN-END:variables
}
