/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vivispizza;

import java.sql.Connection;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import metodos_sql.conexiondb;
import metodos_sql.metodos_sql;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import static vivispizza.login.texto;

/**
 *
 * @author christian
 */
public class Reportes extends javax.swing.JFrame {
private metodos_sql metodos = new metodos_sql();
    /**
     * Creates new form Reportes
     */
    public Reportes() {
        initComponents();
        setLocationRelativeTo(null);
        //Esto trae la fecha de Hoy
        Calendar c2 = new GregorianCalendar();
        JFechaInicio.setCalendar(c2);
        JFechaFin.setCalendar(c2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnventas = new javax.swing.JButton();
        JFechaInicio = new com.toedter.calendar.JDateChooser();
        JFechaFin = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnListado_Productos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reporte");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnventas.setText("Ventas");
        btnventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnventasActionPerformed(evt);
            }
        });
        jPanel1.add(btnventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 159, -1, -1));
        jPanel1.add(JFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 83, 150, -1));
        jPanel1.add(JFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 83, 160, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reportes");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 27, 564, -1));

        jLabel2.setText("Desde");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 89, -1, -1));

        jLabel3.setText("Hasta");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 89, -1, -1));

        btnListado_Productos.setText("Listado de Productos");
        btnListado_Productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListado_ProductosActionPerformed(evt);
            }
        });
        jPanel1.add(btnListado_Productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 159, -1, -1));

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnventasActionPerformed
            SimpleDateFormat dformart=new SimpleDateFormat("dd/MM/yyyy");
            String fecha = dformart.format(JFechaInicio.getDate());
            ParseFecha(fecha);
            java.sql.Date FechaInicio = new java.sql.Date(fechaDate.getTime());
            String fecha2 = dformart.format(JFechaFin.getDate());
            ParseFecha(fecha2);
            java.sql.Date FechaFin = new java.sql.Date(fechaDate.getTime());
           Connection conexion = null;
           try {     
        
            conexion = conexiondb.getConexion();
            JasperReport reporte = null;
            //Este path seria para linux
            //String path = "/mnt/2BB12D737F92C9C5/software vivis pizza/vivispizza/src/Reportes/Reportes_Ventas.jasper";
            //Este path seria para windows
            String path = "C:\\Users\\Christian Avalos\\Documents\\VivisPizza\\src\\Reportes\\Reportes_Ventas.jasper";
            //C:\Users\Christian Avalos\Documents\VivisPizza\src\Reportes
            //Aqui se le pasa el parametro de Fechas
            Map parametro = new HashMap();
            parametro.put("fecha",FechaInicio);
            parametro.put("FechaFin",FechaFin);
        
            
            reporte = (JasperReport) JRLoader.loadObjectFromFile(path);
        
            JasperPrint jprint = JasperFillManager.fillReport(path,parametro,conexion);
                        
            JasperViewer view = new JasperViewer(jprint,false);
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            view.setVisible(true);
        
    } catch (JRException ex) {
        Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnventasActionPerformed

    private void btnListado_ProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListado_ProductosActionPerformed
         try {     
        
            conexiondb conn = new conexiondb();
            Connection con = conn.getConexion(); 
            JasperReport reporte = null;
            //Este path seria para linux
            String path = "/mnt/2BB12D737F92C9C5/software vivis pizza/vivispizza/src/Reportes/Reporte_Tipo_Producto.jasper";
            //Este path seria para windows
            //String path = "D:\\software vivis pizza\\vivispizza\\src\\Reportes\\Reporte_Tipo_Producto.jasper";
         reporte = (JasperReport) JRLoader.loadObjectFromFile(path);
        
            JasperPrint jprint = JasperFillManager.fillReport(path,null,con);
                        
            JasperViewer view = new JasperViewer(jprint,false);
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            view.setVisible(true);
        
    } catch (JRException ex) {
        Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnListado_ProductosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Menu_principal ventana = new Menu_principal();
         if(texto!=null){
               ventana.labelusuario.setText(texto.toUpperCase());
         }
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
 public java.util.Date fechaDate;
    public  java.util.Date ParseFecha(String fecha){
        fechaDate = null;
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        try {
            fechaDate = formato.parse(fecha);  
        } 
        catch (ParseException ex) 
        {
            System.out.println(ex);
        }
        //JOptionPane.showMessageDialog(null,fechaDate.toString());
       // date.setDate(fechaDate);
        
        return fechaDate;
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JFechaFin;
    private com.toedter.calendar.JDateChooser JFechaInicio;
    private javax.swing.JButton btnListado_Productos;
    private javax.swing.JButton btnventas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
